def g: Int = try 42 finally ; // error
