given {    // error
  def foo = 1  // error
} // error